/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    id("org.springframework.boot") version "3.5.6"
    id("io.spring.dependency-management") version "1.1.7"
}

extra["opentelemetry.version"] = libs.versions.io.opentelemetry.bom.get()

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

configurations {
  compileOnly {
    extendsFrom(configurations.annotationProcessor.get())
  }
  all {
    exclude(group = "junit", module = "junit") // Exclude JUnit 4
    exclude(group = "org.springframework.boot", module = "spring-boot-starter-logging")
  }
}

dependencies {
    implementation(enforcedPlatform(libs.io.opentelemetry.bom))
    implementation(enforcedPlatform(libs.io.opentelemetry.instrumentation.bom))
    implementation(libs.org.springframework.boot.spring.boot.starter.web)
    implementation(libs.org.springframework.boot.spring.boot.starter.thymeleaf)
    implementation(libs.org.springframework.boot.spring.boot.starter.data.jpa)
    implementation(libs.org.springframework.boot.spring.boot.starter.validation)
    implementation(libs.org.springframework.boot.spring.boot.starter.actuator)
    implementation(libs.org.springframework.boot.spring.boot.starter.cache)
    implementation(libs.org.projectlombok.lombok)
    annotationProcessor(libs.org.projectlombok.lombok)
    implementation(libs.com.fasterxml.jackson.datatype.jackson.datatype.jsr310)
    implementation(libs.org.apache.commons.commons.lang3)
    implementation(libs.org.xhtmlrenderer.flying.saucer.pdf)
    implementation(libs.com.lowagie.itext)
    implementation(libs.org.jsoup.jsoup)
    implementation(libs.com.microsoft.playwright)
    implementation(libs.org.springframework.boot.spring.boot.starter.log4j2)
    implementation(libs.org.apache.logging.log4j.log4j.api)
    implementation(libs.org.apache.logging.log4j.log4j.core)
    implementation(libs.org.apache.logging.log4j.log4j.slf4j2.impl)
    implementation(libs.org.apache.logging.log4j.log4j.layout.template.json)
    implementation(libs.com.lmax.disruptor)
    implementation(libs.io.opentelemetry.instrumentation.opentelemetry.spring.boot.starter)
    implementation(libs.io.micrometer.context.propagation)
    implementation(libs.io.opentelemetry.opentelemetry.exporter.otlp)
    implementation(libs.io.micrometer.micrometer.registry.prometheus)
    implementation(libs.otel.log4j.context.data)

    // 전자서명 QR 코드 생성
    implementation(libs.com.google.zxing.core)
    implementation(libs.com.google.zxing.javase)

    // 전자서명 실시간 알림 (WebSocket + STOMP)
    implementation(libs.org.springframework.boot.spring.boot.starter.websocket)



    testRuntimeOnly(libs.com.h2database.h2)
    runtimeOnly(libs.org.springframework.boot.spring.boot.devtools)
    runtimeOnly(libs.org.postgresql.postgresql)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
}

group = "com.pinecni"
version = "0.0.1-SNAPSHOT"
description = "groupware"
java.sourceCompatibility = JavaVersion.VERSION_21

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.withType<Test> {
    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
    }
}
